#define TYPE 1
#define NAME 2
#define TABLE_PREFIX 3
#define PORT 4
#define COLON 5
#define IDENTIFIER 6
#define INTEGER 7
#define RESERVED 8
#define WORD_RESERVED 9
#define OARITH 10
#define ARITHMETIC_OPERATOR 11
